### ISSUE TITLE
Not working .

### ISSUE THREAD

**Issue by Spanoudakhs** [hqjs/hq#17]
Steps to reproduce : 

Create a folder and in it execute : 

```js
npm init -y;
npm install -g @hqjs/hq;
```
Then create `./index.html` and in it add : 
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	hello world
</body>
</html>
```
then execute :
```
hq;
```
and go to the localhost prompted by the terminal .
The web page shows this message :
```
File / not found
NotFoundError: File / not found
    at Object.throw (/home/lillallol/.nvm/versions/node/v14.5.0/lib/node_modules/@hqjs/hq/node_modules/koa/lib/context.js:97:11)
    at resolveSrc (file:///home/lillallol/.nvm/versions/node/v14.5.0/lib/node_modules/@hqjs/hq/middlewares/resolve-path.mjs:116:31)
    at async file:///home/lillallol/.nvm/versions/node/v14.5.0/lib/node_modules/@hqjs/hq/middlewares/resolve-path.mjs:36:5
    at async cors (/home/lillallol/.nvm/versions/node/v14.5.0/lib/node_modules/@hqjs/hq/node_modules/@koa/cors/index.js:56:32)
    at async file:///home/lillallol/.nvm/versions/node/v14.5.0/lib/node_modules/@hqjs/hq/middlewares/error-handler.mjs:5:5
```

**Comment by hqjs** [comment]
Point `main` field in your `package.json` to `index.html` or remove it completely. Otherwise you will have to specify `/index.html` as a part of the URL.

**Comment by Spanoudakhs** [comment]
@hqjs I added `/index.html` at the end of the url and it works . Thx .
