### ISSUE TITLE
Error resolving module specifier in raw tsc --init project

### ISSUE THREAD

**Issue by Zageron** [hqjs/hq#24]
```
Uncaught TypeError: Error resolving module specifier “\render”. Relative module specifiers must start with “./”, “../” or “/”.
```
typescript 4.0.3
node 12.18.4 or 14.12.0

The most basic of basic typescript projects seem to be broken now. This wasn't broken the last time I was playing with this project.
![image](https://user-images.githubusercontent.com/1892473/94227799-41365380-feb0-11ea-978d-21853c0b3a5f.png)

**Comment by hqjs** [comment]
Hey! thanks for reporting! It seems like some windows specific error as it expects `/render`, but got `\render` instead. I'll take a look.

**Comment by hqjs** [comment]
@Zageron can you please give me the output of `hq --verbose` and separate results of requesting `/render.ts` and `/index.ts`?

**Comment by Zageron** [comment]
Specifically requesting `http://localhost:8080/` and startup.
```bash
L:\git\zageron\tinkering>hq --verbose
(c) hqjs @ 0.0.23
Start time: 0.2 s

Visit http://localhost:8080
or http://192.168.1.239:8080 within local network

�  USER AGENT Firefox 81.0 for desktop

✔️   SUPPORT    true

�  RESOLVE    \index.html: L:\git\zageron\tinkering\src\index.html 0b

ℹ️   STATS      /: text/html source

�   ETAG       /: version 0 - 200 OK

�️   BUILD      /: Firefox 81.0 for desktop

�  SEND       /

�  RESOLVE    /stylesheets/style.scss: L:\git\zageron\tinkering\src\stylesheets\style.scss 198b

ℹ️   STATS      /stylesheets/style.scss: text/css source
�   ETAG       /stylesheets/style.scss: version 0 - 200 OK
�️   BUILD      /stylesheets/style.scss: Firefox 81.0 for desktop
�  RESOLVE    /index.ts: L:\git\zageron\tinkering\src\index.ts 46b

ℹ️   STATS      /index.ts: application/javascript source
�   ETAG       /index.ts: version 0 - 200 OK
�️   BUILD      /index.ts: Firefox 81.0 for desktop

�  RESOLVE    /hq-livereload.js: C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq/hq-livereload.js 207b

ℹ️   STATS      /hq-livereload.js: application/javascript source
�   ETAG       /hq-livereload.js: version 0 - 200 OK
�️   BUILD      /hq-livereload.js: Firefox 81.0 for desktop

�  SEND       /index.ts

�  SEND       /hq-livereload.js

�  SEND       /stylesheets/style.scss

�  RESOLVE    /favicon.ico: C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq/hqjs.png 413b

ℹ️   STATS      /favicon.ico: image/png asset
�   ETAG       /favicon.ico: version 0 - 200 OK
�️   BUILD      /favicon.ico: Firefox 81.0 for desktop

�  SEND       /favicon.ico

�  RESOLVE    /index.ts.map: virtual

ℹ️   STATS      /index.ts.map: application/json source
�   ETAG       /index.ts.map: version 0 - 200 OK
⚙️   CACHE      /index.ts.map: Firefox 81.0 for desktop
�  SEND       /index.ts.map

�️   COMPRESS   /index.ts.map

�  RESOLVE    /index.ts.map: virtual

ℹ️   STATS      /index.ts.map: application/json source
�   ETAG       /index.ts.map: version 0 - 304 Not Modified
```

Specifically requesting `http://localhost:8080/index.ts`
``` 
�  RESOLVE    /index.ts: L:\git\zageron\tinkering\src\index.ts 46b

ℹ️   STATS      /index.ts: application/javascript source
�   ETAG       /index.ts: version 0 - 304 Not Modified
```

Page output for `index.ts`
```
let Render;
import * as _ref from "\\render";

try {
  Render = "Render" in _ref ? _ref.Render : _ref.default.Render;
} catch {
  Promise.resolve().then(() => (Render = "Render" in _ref ? _ref.Render : _ref.default.Render)).catch(() => console.error("Unable to resolve cyclic dependencies between module \"L:\\index.ts.map*\" and \"\\render.map*\" while requesting \"Render as Render\". Try to import \"L:\\index.ts\" before \"\\render\" in a parent module"));
}

Render();
//# sourceMappingURL=/index.ts.map
```

Specifically requesting `http://localhost:8080/render.ts`
```
�  RESOLVE    /render.ts: L:\git\zageron\tinkering\src\render.ts 96b

ℹ️   STATS      /render.ts: application/javascript source
�   ETAG       /render.ts: version 0 - 304 Not Modified
```

Page output for `render.ts`
```
function Render() {
  console.log("Draw special awesome thing. again");
}

export { Render };
//# sourceMappingURL=/render.ts.map
```

When running in WSL it finds and builds everything correctly. (But as in previous issue auto-reload doesn't work).
When running in Windows it fails to find Render.ts, but auto-reload works for everything in index.ts and index.html.

**Comment by Zageron** [comment]
Sorry for the small discrepancy in folder layouts, the output is the same for `tinkering` and `scratch` I just created the same project from scratch (no copying) to make sure it wasn't some weird state error.

**Comment by hqjs** [comment]
Thanks a lot for the detailed logs. Usually just a problem statement is enough, but I have no windows machine so it is much easier with the log in this case. I'm going for vacation tomorrow, will try to find the issue before that. Sorry for inconvenience.

**Comment by hqjs** [comment]
Ok, I have an assumption that this is connected to path-resolution where `dirname` is calculated. In case if I won't be able to fix it before the vacation - please try to implicitly ask for `http://localhost:8080/index.html`. It might help, but I see the risk it might not work with `node_modules`.

**Comment by Zageron** [comment]
Unfortunately it made no difference. The output still shows no mention of render.ts. :)

**Comment by hqjs** [comment]
Hey, can you please test new version `0.0.24` so I will be able to release supplementary VSCode plugin?

**Comment by Zageron** [comment]
`http://localhost:8081/`
`GEThttp://localhost:8081/`

Identical behaviour at
`http://localhost:8081/index.html`
`http://localhost:8081/render.ts`

```bash
L:\git\zageron\scratch>hq --verbose
(c) hqjs @ 0.0.24
Start time: 0.2 s

Visit http://localhost:8081
or http://192.168.1.239:8081 within local network


| hq root    : C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq

| root       : L:\git\zageron\scratch
| src        : src

| certs      :

| babelrc    : undefined
| postcssrc  : undefined
| posthtmlrc : undefined


�  USER AGENT Firefox 81.0 for desktop

✔️   SUPPORT    true

❌ Error /: File / not found

NotFoundError: File / not found
    at Object.throw (C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\koa\lib\context.js:97:11)
    at resolveSrc (file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/resolve-path.mjs:128:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/resolve-path.mjs:37:5
    at async cors (C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\@koa\cors\index.js:56:32)
    at async file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/error-handler.mjs:5:5

�  RESOLVE    /favicon.ico: C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq/hqjs.png 413b

ℹ️   STATS      /favicon.ico: image/png asset

�   ETAG       /favicon.ico: version 0 - 200 OK

�️   BUILD      /favicon.ico: Firefox 81.0 for desktop

�  SEND       /favicon.ico
```

**Comment by hqjs** [comment]
@Zageron Can you please run node in the project root
```sh
node
```
And then execute few lines of code to test how it works on Windows system?
```js
url = require('url');
path = require('path');
urlToPath = urlPath => url.fileURLToPath(urlPath.startsWith('file://') ? urlPath : `file://${urlPath}`);
console.log(urlToPath('/index.html'));
console.log(path.join('src', urlToPath('/index.html')));
console.log(path.resolve('L:\git\zageron\scratch', path.join('src', urlToPath('/index.html'))));
```

**Comment by Zageron** [comment]
```bash
L:\git\zageron\scratch>node
Welcome to Node.js v14.10.0.
Type ".help" for more information.
> url = require('url');
{
  Url: [Function: Url],
  parse: [Function: urlParse],
  resolve: [Function: urlResolve],
  resolveObject: [Function: urlResolveObject],
  format: [Function: urlFormat],
  URL: [class URL],
  URLSearchParams: [class URLSearchParams],
  domainToASCII: [Function: domainToASCII],
  domainToUnicode: [Function: domainToUnicode],
  pathToFileURL: [Function: pathToFileURL],
  fileURLToPath: [Function: fileURLToPath]
}
> path = require('path');
<ref *1> {
  resolve: [Function: resolve],
  normalize: [Function: normalize],
  isAbsolute: [Function: isAbsolute],
  join: [Function: join],
  relative: [Function: relative],
  toNamespacedPath: [Function: toNamespacedPath],
  dirname: [Function: dirname],
  basename: [Function: basename],
  extname: [Function: extname],
  format: [Function: bound _format],
  parse: [Function: parse],
  sep: '\\',
  delimiter: ';',
  win32: [Circular *1],
  posix: <ref *2> {
    resolve: [Function: resolve],
    normalize: [Function: normalize],
    isAbsolute: [Function: isAbsolute],
    join: [Function: join],
    relative: [Function: relative],
    toNamespacedPath: [Function: toNamespacedPath],
    dirname: [Function: dirname],
    basename: [Function: basename],
    extname: [Function: extname],
    format: [Function: bound _format],
    parse: [Function: parse],
    sep: '/',
    delimiter: ':',
    win32: [Circular *1],
    posix: [Circular *2],
    _makeLong: [Function: toNamespacedPath]
  },
  _makeLong: [Function: toNamespacedPath]
}
> urlToPath = urlPath => url.fileURLToPath(urlPath.startsWith('file://') ? urlPath : `file://${urlPath}`);
[Function: urlToPath]
> console.log(urlToPath('/index.html'));
Uncaught TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at getPathFromURLWin32 (internal/url.js:1321:11)
    at Object.fileURLToPath (internal/url.js:1351:22)
    at urlToPath (REPL3:1:28)
    at REPL4:1:13
    at Script.runInThisContext (vm.js:132:18)
    at REPLServer.defaultEval (repl.js:479:29)
    at bound (domain.js:430:14)
    at REPLServer.runBound [as eval] (domain.js:443:12)
    at REPLServer.onLine (repl.js:809:10)
    at REPLServer.emit (events.js:326:22) {
  code: 'ERR_INVALID_FILE_URL_PATH'
}
> console.log(path.join('src', urlToPath('/index.html')));
Uncaught TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at getPathFromURLWin32 (internal/url.js:1321:11)
    at Object.fileURLToPath (internal/url.js:1351:22)
    at urlToPath (REPL3:1:28)
    at REPL5:1:30
    at Script.runInThisContext (vm.js:132:18)
    at REPLServer.defaultEval (repl.js:479:29)
    at bound (domain.js:430:14)
    at REPLServer.runBound [as eval] (domain.js:443:12)
    at REPLServer.onLine (repl.js:809:10)
    at REPLServer.emit (events.js:326:22) {
  code: 'ERR_INVALID_FILE_URL_PATH'
}
> console.log(path.resolve('L:\git\zageron\scratch', path.join('src', urlToPath('/index.html'))));
Uncaught TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at getPathFromURLWin32 (internal/url.js:1321:11)
    at Object.fileURLToPath (internal/url.js:1351:22)
    at urlToPath (REPL3:1:28)
    at REPL6:1:69
    at Script.runInThisContext (vm.js:132:18)
    at REPLServer.defaultEval (repl.js:479:29)
    at bound (domain.js:430:14)
    at REPLServer.runBound [as eval] (domain.js:443:12)
    at REPLServer.onLine (repl.js:809:10)
    at REPLServer.emit (events.js:326:22) {
  code: 'ERR_INVALID_FILE_URL_PATH'
}
```

**Comment by hqjs** [comment]
Thanks a lot! Windows is hard. What if we change it to this lines?
```js
url = require('url');
path = require('path');
urlToPath = urlPath => url.fileURLToPath(urlPath.startsWith('file:/') ? urlPath : `file:/${urlPath}`);
console.log(urlToPath('/index.html'));
console.log(path.join('src', urlToPath('/index.html')));
console.log(path.resolve('L:\git\zageron\scratch', path.join('src', urlToPath('/index.html'))));
```

**Comment by Zageron** [comment]
```cmd
L:\git\zageron\scratch>node
Welcome to Node.js v14.10.0.
Type ".help" for more information.
> url = require('url');
(path.resolve('L:\git\zageron\scratch', path.join('src', urlToPath('/index.html'))));{
  Url: [Function: Url],
  parse: [Function: urlParse],
  resolve: [Function: urlResolve],
  resolveObject: [Function: urlResolveObject],
  format: [Function: urlFormat],
  URL: [class URL],
  URLSearchParams: [class URLSearchParams],
  domainToASCII: [Function: domainToASCII],
  domainToUnicode: [Function: domainToUnicode],
  pathToFileURL: [Function: pathToFileURL],
  fileURLToPath: [Function: fileURLToPath]
}
> path = require('path');
<ref *1> {
  resolve: [Function: resolve],
  normalize: [Function: normalize],
  isAbsolute: [Function: isAbsolute],
  join: [Function: join],
  relative: [Function: relative],
  toNamespacedPath: [Function: toNamespacedPath],
  dirname: [Function: dirname],
  basename: [Function: basename],
  extname: [Function: extname],
  format: [Function: bound _format],
  parse: [Function: parse],
  sep: '\\',
  delimiter: ';',
  win32: [Circular *1],
  posix: <ref *2> {
    resolve: [Function: resolve],
    normalize: [Function: normalize],
    isAbsolute: [Function: isAbsolute],
    join: [Function: join],
    relative: [Function: relative],
    toNamespacedPath: [Function: toNamespacedPath],
    dirname: [Function: dirname],
    basename: [Function: basename],
    extname: [Function: extname],
    format: [Function: bound _format],
    parse: [Function: parse],
    sep: '/',
    delimiter: ':',
    win32: [Circular *1],
    posix: [Circular *2],
    _makeLong: [Function: toNamespacedPath]
  },
  _makeLong: [Function: toNamespacedPath]
}
> urlToPath = urlPath => url.fileURLToPath(urlPath.startsWith('file:/') ? urlPath : `file:/${urlPath}`);
[Function: urlToPath]
> console.log(urlToPath('/index.html'));
\\index.html\
undefined
> console.log(path.join('src', urlToPath('/index.html')));
src\index.html\
undefined
> console.log(path.resolve('L:\git\zageron\scratch', path.join('src', urlToPath('/index.html'))));
L:\git\zageron\scratch\gitzageronscratch\src\index.html
undefined
```

**Comment by hqjs** [comment]
Bingo! It looks like what we need. I'll add exception for windows and release in couple of minutes.

**Comment by hqjs** [comment]
Please try `0.0.25`

**Comment by Zageron** [comment]
`http://localhost:8080/` Fail
`http://localhost:8080/index.html` "Succeed"

Logs in Firefox:
```
Loading module from “http://localhost:8080/hq-livereload.js” was blocked because of a disallowed MIME type (“text/plain”).
index.html
Loading failed for the module with source “http://localhost:8080/hq-livereload.js”. index.html:14:1
Loading module from “http://localhost:8080/index.ts” was blocked because of a disallowed MIME type (“text/plain”).
index.html
Loading failed for the module with source “http://localhost:8080/index.ts”. index.html:11:1
```

```cmd
L:\git\zageron\scratch>hq --verbose
(c) hqjs @ 0.0.25
Start time: 0.2 s

Visit http://localhost:8080
or http://192.168.1.239:8080 within local network


| hq root    : C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq

| root       : L:\git\zageron\scratch
| src        : src

| certs      :

| babelrc    : undefined
| postcssrc  : undefined
| posthtmlrc : undefined


�  USER AGENT Firefox 81.0 for desktop

✔️   SUPPORT    true

❌ Error /: File / not found

NotFoundError: File / not found
    at Object.throw (C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\koa\lib\context.js:97:11)
    at resolveSrc (file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/resolve-path.mjs:128:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/resolve-path.mjs:37:5
    at async cors (C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\@koa\cors\index.js:56:32)
    at async file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/error-handler.mjs:5:5

�  RESOLVE    /index.html: L:\git\zageron\scratch\src\index.html 358b

ℹ️   STATS      /index.html: text/html source

�   ETAG       /index.html: version 0 - 200 OK

�️   BUILD      /index.html: Firefox 81.0 for desktop

�  SEND       /index.html

�  RESOLVE    /hq-livereload.js: C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq\hq-livereload.js\ 207b

ℹ️   STATS      /hq-livereload.js: application/javascript source
�   ETAG       /hq-livereload.js: version 0 - 200 OK
�️   BUILD      /hq-livereload.js: Firefox 81.0 for desktop

�  RESOLVE    /index.ts: L:\git\zageron\scratch\src\index.ts 120b

ℹ️   STATS      /index.ts: application/javascript source
�   ETAG       /index.ts: version 0 - 200 OK
�️   BUILD      /index.ts: Firefox 81.0 for desktop

❌ Error /hq-livereload.js: File URL path must be absolute

TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at getPathFromURLWin32 (internal/url.js:1321:11)
    at Object.fileURLToPath (internal/url.js:1351:22)
    at urlToPath (file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/utils.mjs:67:11)
    at compileJS (file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/compilers/js.mjs:567:72)
    at async buildSource (file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/build.mjs:21:13)
    at async file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/build.mjs:107:5
    at async cors (C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\@koa\cors\index.js:56:32)
    at async file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/error-handler.mjs:5:5


  TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
      at getPathFromURLWin32 (internal/url.js:1321:11)
      at Object.fileURLToPath (internal/url.js:1351:22)
      at urlToPath (file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/utils.mjs:67:11)
      at compileJS (file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/compilers/js.mjs:567:72)
      at async buildSource (file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/build.mjs:21:13)
      at async file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/build.mjs:107:5
      at async cors (C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\@koa\cors\index.js:56:32)
      at async file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/error-handler.mjs:5:5


❌ Error /index.ts: File URL path must be absolute

TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at getPathFromURLWin32 (internal/url.js:1321:11)
    at Object.fileURLToPath (internal/url.js:1351:22)
    at urlToPath (file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/utils.mjs:67:11)
    at compileJS (file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/compilers/js.mjs:567:72)
    at async buildSource (file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/build.mjs:21:13)
    at async file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/build.mjs:107:5
    at async cors (C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\@koa\cors\index.js:56:32)
    at async file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/error-handler.mjs:5:5


  TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
      at getPathFromURLWin32 (internal/url.js:1321:11)
      at Object.fileURLToPath (internal/url.js:1351:22)
      at urlToPath (file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/utils.mjs:67:11)
      at compileJS (file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/compilers/js.mjs:567:72)
      at async buildSource (file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/build.mjs:21:13)
      at async file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/build.mjs:107:5
      at async cors (C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\@koa\cors\index.js:56:32)
      at async file:///C:/Users/Zageron/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/error-handler.mjs:5:5
```

**Comment by hqjs** [comment]
Remote debugging is painful. Hope `0.0.26` will work. I honestly do not understand why it's not working without `index.html`, but let's try and see.

**Comment by Zageron** [comment]
Hooray.

```cmd
L:\git\zageron\scratch>hq --verbose
(c) hqjs @ 0.0.26
Start time: 0.3 s

Visit http://localhost:8080
or http://192.168.1.239:8080 within local network


| hq root    : C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq

| root       : L:\git\zageron\scratch
| src        : src

| certs      :

| babelrc    : undefined
| postcssrc  : undefined
| posthtmlrc : undefined


�  USER AGENT Firefox 81.0 for desktop

✔️   SUPPORT    true

�  RESOLVE    /: L:\git\zageron\scratch\src\index.html 0b

ℹ️   STATS      /: text/html source

�   ETAG       /: version 0 - 200 OK

�️   BUILD      /: Firefox 81.0 for desktop

�  SEND       /

�  RESOLVE    /hq-livereload.js: C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq\hq-livereload.js 207b

ℹ️   STATS      /hq-livereload.js: application/javascript source
�   ETAG       /hq-livereload.js: version 0 - 200 OK
�️   BUILD      /hq-livereload.js: Firefox 81.0 for desktop

�  RESOLVE    /index.ts: L:\git\zageron\scratch\src\index.ts 120b

ℹ️   STATS      /index.ts: application/javascript source
�   ETAG       /index.ts: version 0 - 200 OK
�️   BUILD      /index.ts: Firefox 81.0 for desktop

�  SEND       /hq-livereload.js

�  SEND       /index.ts

�  RESOLVE    /render: L:\git\zageron\scratch\src\render.ts NaNMb

ℹ️   STATS      /render: application/javascript source
�   ETAG       /render: version 0 - 200 OK
�️   BUILD      /render: Firefox 81.0 for desktop

�  SEND       /render

�  RESOLVE    /render.map: virtual

ℹ️   STATS      /render.map: application/json source
�   ETAG       /render.map: version 0 - 200 OK
⚙️   CACHE      /render.map: Firefox 81.0 for desktop
�  SEND       /render.map

�️   COMPRESS   /render.map

�  RESOLVE    /index.ts.map: virtual

ℹ️   STATS      /index.ts.map: application/json source
�   ETAG       /index.ts.map: version 0 - 200 OK
⚙️   CACHE      /index.ts.map: Firefox 81.0 for desktop
�  SEND       /index.ts.map

�️   COMPRESS   /index.ts.map

� Reloaded



�  RESOLVE    /: L:\git\zageron\scratch\src\index.html 0b

ℹ️   STATS      /: text/html source
�   ETAG       /: version 0 - 304 Not Modified

�  RESOLVE    /index.ts: L:\git\zageron\scratch\src\index.ts 120b

ℹ️   STATS      /index.ts: application/javascript source
�   ETAG       /index.ts: version 1 - 200 OK
�️   BUILD      /index.ts: Firefox 81.0 for desktop

�  RESOLVE    /hq-livereload.js: C:\Users\Zageron\AppData\Roaming\npm\node_modules\@hqjs\hq\hq-livereload.js 207b
ℹ️   STATS      /hq-livereload.js: application/javascript source

�   ETAG       /hq-livereload.js: version 0 - 304 Not Modified

�  SEND       /index.ts

�  RESOLVE    /render: L:\git\zageron\scratch\src\render.ts NaNMb

ℹ️   STATS      /render: application/javascript source
�   ETAG       /render: version 0 - 304 Not Modified

�  RESOLVE    /index.ts.map: virtual
ℹ️   STATS      /index.ts.map: application/json source

�   ETAG       /index.ts.map: version 2 - 200 OK
⚙️   CACHE      /index.ts.map: Firefox 81.0 for desktop
�  SEND       /index.ts.map

�️   COMPRESS   /index.ts.map

�  RESOLVE    /render.map: virtual

ℹ️   STATS      /render.map: application/json source
�   ETAG       /render.map: version 0 - 304 Not Modified
```

**Comment by Zageron** [comment]
Thanks so much for resolving this for me right before your vacation! :D
