### ISSUE TITLE
Error start

### ISSUE THREAD

**Issue by SergeyLitvin** [hqjs/hq#30]
I start the project.

`<!doctype html>
<html lang="en">
<head>
  <link rel="stylesheet" href="styles/main.css">
</head>
<body>

  <script src="js/main.js"></script>
</body>
</html>`

main.js
`console.log('test_hq');`

And run command hq

And I get the error
`(intermediate value)(intermediate value)(intermediate value) is not iterable
TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable
    at file:///C:/Users/Serg/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/check-support.mjs:27:44
    at dispatch (C:\Users\Serg\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\koa-compose\index.js:42:32)
    at file:///C:/Users/Serg/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/detect-ua.mjs:46:10
    at dispatch (C:\Users\Serg\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\koa-compose\index.js:42:32)
    at cors (C:\Users\Serg\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\@koa\cors\index.js:56:38)
    at dispatch (C:\Users\Serg\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\koa-compose\index.js:42:32)
    at file:///C:/Users/Serg/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/error-handler.mjs:5:11
    at dispatch (C:\Users\Serg\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\koa-compose\index.js:42:32)
    at C:\Users\Serg\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\koa-compose\index.js:34:12
    at dispatch (C:\Users\Serg\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\koa-compose\index.js:42:32)`

My environment:
Edition	Windows 10 Home
Version	20H2
Installed on	‎09/‎26/‎2020
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0

NodeJS - v14.13.1
npm - 6.14.8
hq - 0.0.31

Please help me!

**Comment by hqjs** [comment]
Hey! thanks for reporting. Is it an error you get on a start or after accessing http://localhos:8000? Can you please run the server with `hq --verbose` command and post an output here?

**Comment by hqjs** [comment]
What browser are you using for development? Seems like it is not something standard.

**Comment by SergeyLitvin** [comment]
> Hey! thanks for reporting. Is it an error you get on a start or after accessing http://localhos:8000? Can you please run the server with `hq --verbose` command and post an output here?

`hq --verbose
(c) hqjs @ 0.0.31
Start time: 0.3 s

Visit http://localhost:8080
or http://192.168.31.160:8080 within local network


| hq root    : C:\Users\Serg\AppData\Roaming\npm\node_modules\@hqjs\hq

| root       : D:\((___PROJECTS___))\MY\test_hq
| src        : .

| certs      : 

| babelrc    : undefined
| postcssrc  : undefined
| posthtmlrc : undefined`

https://bit.ly/2N25Q6C

**Comment by SergeyLitvin** [comment]
> What browser are you using for development? Seems like it is not something standard.

If I run http://localhost:8080/ in the Yandex browser I get an error. 
If I open in Google Chrome and the project starts well. - https://bit.ly/2Zf3N1C

**Comment by SergeyLitvin** [comment]
Thanks a lot that helped to understand and launch the project. I will try to use HQ.

**Comment by hqjs** [comment]
That's actually a good idea to start supporting Yandex browser as well as treating all unknown browsers as some basic version of chrome. Don't hesitate to contact me if you'll experience any problems. You might be interested in https://pkg.hqjs.org it is demo installation (and might disappear once in a while as it is running on a very low end machine), but local installation is also possible to help you deal with microservice frontend architecture.

**Comment by SergeyLitvin** [comment]
Please tell me if the automatic restart of the browser should work after saving the files in the editor?

`
$ hq --verbose
(c) hqjs @ 0.0.31
Start time: 0.5 s

Visit http://localhost:8080
or http://192.168.31.160:8080 within local network


| hq root    : C:\Users\Serg\AppData\Roaming\npm\node_modules\@hqjs\hq

| root       : D:\((___PROJECTS___))\MY\test_hq
| src        : .

| certs      :

| babelrc    : undefined
| postcssrc  : undefined
| posthtmlrc : undefined


🌐  USER AGENT Chrome 88.0 for desktop

✔️   SUPPORT    true

🔎  RESOLVE    /: D:\((___PROJECTS___))\MY\test_hq\index.html 196b

ℹ️   STATS      /: text/html source

🏷   ETAG       /: version 0 - 200 OK

🛠️   BUILD      /: Chrome 88.0 for desktop

🚀  SEND       /

🔎  RESOLVE    /styles/main.css: D:\((___PROJECTS___))\MY\test_hq\styles\main.css 0b

ℹ️   STATS      /styles/main.css: text/css source
🏷   ETAG       /styles/main.css: version 0 - 200 OK
🛠️   BUILD      /styles/main.css: Chrome 88.0 for desktop

🔎  RESOLVE    /js/main.js: D:\((___PROJECTS___))\MY\test_hq\js\main.js 317b
ℹ️   STATS      /js/main.js: application/javascript source
🏷   ETAG       /js/main.js: version 0 - 200 OK
🛠️   BUILD      /js/main.js: Chrome 88.0 for desktop

🚀  SEND       /styles/main.css

🔎  RESOLVE    /hq-livereload.js: C:\Users\Serg\AppData\Roaming\npm\node_modules\@hqjs\hq\hq-livereload.js 207b

ℹ️   STATS      /hq-livereload.js: application/javascript source
🏷   ETAG       /hq-livereload.js: version 0 - 200 OK
🛠️   BUILD      /hq-livereload.js: Chrome 88.0 for desktop

🚀  SEND       /js/main.js

🚀  SEND       /hq-livereload.js

🔎  RESOLVE    /node_modules/react-dom: D:\((___PROJECTS___))\MY\test_hq\node_modules\react-dom\index.js 1.3Kb

ℹ️   STATS      /node_modules/react-dom: application/javascript source
🏷   ETAG       /node_modules/react-dom: version 0 - 200 OK
🛠️   BUILD      /node_modules/react-dom: Chrome 88.0 for desktop
🔎  RESOLVE    /node_modules/react: D:\((___PROJECTS___))\MY\test_hq\node_modules\react\index.js 190b
ℹ️   STATS      /node_modules/react: application/javascript source
🏷   ETAG       /node_modules/react: version 0 - 200 OK
🛠️   BUILD      /node_modules/react: Chrome 88.0 for desktop

🚀  SEND       /node_modules/react-dom

🗜️   COMPRESS   /node_modules/react-dom

🚀  SEND       /node_modules/react

🔎  RESOLVE    /node_modules/react/cjs/react.development.js: D:\((___PROJECTS___))\MY\test_hq\node_modules\react\cjs\react.development.js 70.5Kb    

ℹ️   STATS      /node_modules/react/cjs/react.development.js: application/javascript source
🏷   ETAG       /node_modules/react/cjs/react.development.js: version 0 - 200 OK
🛠️   BUILD      /node_modules/react/cjs/react.development.js: Chrome 88.0 for desktop
🔎  RESOLVE    /node_modules/react-dom/cjs/react-dom.development.js: D:\((___PROJECTS___))\MY\test_hq\node_modules\react-dom\cjs\react-dom.development.js 873.6Kb
ℹ️   STATS      /node_modules/react-dom/cjs/react-dom.development.js: application/javascript source
🏷   ETAG       /node_modules/react-dom/cjs/react-dom.development.js: version 0 - 200 OK
🛠️   BUILD      /node_modules/react-dom/cjs/react-dom.development.js: Chrome 88.0 for desktop

🚀  SEND       /node_modules/react/cjs/react.development.js

🗜️   COMPRESS   /node_modules/react/cjs/react.development.js

🚀  SEND       /node_modules/react-dom/cjs/react-dom.development.js

🗜️   COMPRESS   /node_modules/react-dom/cjs/react-dom.development.js


  Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
`

**Comment by hqjs** [comment]
Live reload should work. Can you please describe in more details what is the use case? Are you saving several files at once or one by one?
