### ISSUE TITLE
Does not follow symlinks while being used with lerna

### ISSUE THREAD

**Issue by yuri-karadzhov** [hqjs/hq#5]
Here is the error:
```js
(c) hqjs @ 0.0.7
Start time: 0.7 s
Visit http://localhost:8081
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event at:
    at fs.read (fs.js:2146:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:603:17)
```

**Comment by hqjs** [comment]
Thanks for reporting. Path resolution is fixed in master and will be available in the next release.
